from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def home(request):
  context = {
    'page_title': 'Function-Based View',
    'page_heading': 'Welcome to the our website',
    'page_content': 'This is the content generated by the function-based view.',
  }
  return render(request, 'home.html', context)

def about_view(request):
  context = {
    'page_title': 'Function-Based View',
    'page_heading': 'Welcome to the our Django page V',
    'page_content': 'This is the content generated by the function-based view.',
  }
  return render(request, 'about.html', context)
def function_view(request):
  context = {
      'page_title': 'Function-Based View',
      'page_heading': 'Welcome to the Function-Based View',
      'page_content': 'This is the content generated by the function-based view.',
  }
  return render(request, 'bootswatch.html', context)

def news_view(request):
  context = {
      'page_title': 'Former presdunt Doland Tramp',
      'page_heading': 'Trump posts nearly $92 million bond in E. Jean Carroll defamation case',
      'page_content': 'This is the content generated by the function-based view.',
  }
  return render(request, 'news.html', context)

def climate_veiw(request):
  context = {
      'page_title': 'Now a day the climte change',
      'page_heading':' What Is Climate Change?',
      'page_content': 'Climate change is a long-term change in the average weather patterns that have come to define Earth’s local, regional and global climates. These changes have a broad range of observed effects that are synonymous with the term.',
  }
  return render(request, 'climate.html', context)
  
def health_veiw(request):
        context = {
            'page_title': 'About health',
            'page_heading':' What is health?',
            'page_content': 'This means that health is a resource to support an individual’s function in wider society, rather than an end in itself. A healthful lifestyle provides the means to lead a full life with meaning and purpose..',
        }
        return render(request, 'health.html', context)
  
def business_veiw(request):
    context = {
        'page_title': 'Function-Based View',
        'page_heading':' What Is Climate Change?',
        'page_content': '"The coveted Southwest Companion Pass is an elite travel benefit that’s almost too good to be true. This pass allows another passenger to fly with you for free (plus taxes) an unlimited number of times for the life of the pass. Traditionally, the pass is valid for the rest of the year it’s earned, plus the entire following year".',
    }
    return render(request, 'busines.html', context)

  

#class from which all class based views inherit
class BaseView(TemplateView):
    default_title = 'My Website'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.setdefault('title', self.default_title)
        return context

class ClassView(BaseView):
  template_name = 'bootswatch.html'

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context.update({
          'title': 'Class-Based View',
          'page_heading': 'Welcome to the Class-Based View',
          'page_content': 'This is the content generated by the class-based view.',
      })
      return context
class ThemeView(BaseView):
      template_name = 'theme.html'

      def get_context_data(self, **kwargs):
          context = super().get_context_data(**kwargs)
          # Add additional context data if needed
          return context

      def post(self, request, *args, **kwargs):
          theme = request.POST.get('theme')
          response = HttpResponseRedirect(reverse('theme'))
          response.set_cookie('theme', theme)
          return response


     
